name: Nix

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Build package
        run: nix build --no-link --print-build-logs
